name: Deploy to GKE

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    name: Deploy to GKE Autopilot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_CLUSTER_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Kubeconfig permissions
        run: |
          mkdir -p ~/.kube
          touch ~/.kube/config

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
